In [1]:
from datasets import load_dataset

dataset = load_dataset("lavita/MedQuAD")

In [2]:
print(dataset)

DatasetDict({
    train: Dataset({
        features: ['document_id', 'document_source', 'document_url', 'category', 'umls_cui', 'umls_semantic_types', 'umls_semantic_group', 'synonyms', 'question_id', 'question_focus', 'question_type', 'question', 'answer'],
        num_rows: 47441
    })
})

In [3]:
print(dataset["train"][0])

{'document_id': '0000559', 'document_source': 'GHR', 'document_url': 'https://ghr.nlm.nih.gov/condition/keratoderma-with-woolly-hair', 'category': None, 'umls_cui': 'C0343073', 'umls_semantic_types': 'T047', 'umls_semantic_group': 'Disorders', 'synonyms': 'KWWH', 'question_id': '0000559-1', 'question_focus': 'keratoderma with woolly hair', 'question_type': 'information', 'question': 'What is (are) keratoderma with woolly hair ?', 'answer': 'Keratoderma with woolly hair is a group of related conditions that affect the skin and hair and in many cases increase the risk of potentially life-threatening heart problems. People with these conditions have hair that is unusually coarse, dry, fine, and tightly curled. In some cases, the hair is also sparse. The woolly hair texture typically affects only scalp hair and is present from birth. Starting early in life, affected individuals also develop palmoplantar keratoderma, a condition that causes skin on the palms of the hands and the soles of the feet to become thick, scaly, and calloused.  Cardiomyopathy, which is a disease of the heart muscle, is a life-threatening health problem that can develop in people with keratoderma with woolly hair. Unlike the other features of this condition, signs and symptoms of cardiomyopathy may not appear until adolescence or later. Complications of cardiomyopathy can include an abnormal heartbeat (arrhythmia), heart failure, and sudden death.  Keratoderma with woolly hair comprises several related conditions with overlapping signs and symptoms. Researchers have recently proposed classifying keratoderma with woolly hair into four types, based on the underlying genetic cause. Type I, also known as Naxos disease, is characterized by palmoplantar keratoderma, woolly hair, and a form of cardiomyopathy called arrhythmogenic right ventricular cardiomyopathy (ARVC). Type II, also known as Carvajal syndrome, has hair and skin abnormalities similar to type I but features a different form of cardiomyopathy, called dilated left ventricular cardiomyopathy. Type III also has signs and symptoms similar to those of type I, including ARVC, although the hair and skin abnormalities are often milder. Type IV is characterized by palmoplantar keratoderma and woolly and sparse hair, as well as abnormal fingernails and toenails. Type IV does not appear to cause cardiomyopathy.'}

In [4]:
import pandas as pd

df = pd.DataFrame(dataset["train"])
df.head()

,document_id,document_source,document_url,category,umls_cui,umls_semantic_types,umls_semantic_group,synonyms,question_id,question_focus,question_type,question,answer
0,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-1,keratoderma with woolly hair,information,What is (are) keratoderma with woolly hair ?,Keratoderma with woolly hair is a group of rel...
1,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-2,keratoderma with woolly hair,frequency,How many people are affected by keratoderma wi...,Keratoderma with woolly hair is rare; its prev...
2,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-3,keratoderma with woolly hair,genetic changes,What are the genetic changes related to kerato...,"Mutations in the JUP, DSP, DSC2, and KANK2 gen..."
3,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-4,keratoderma with woolly hair,inheritance,Is keratoderma with woolly hair inherited ?,Most cases of keratoderma with woolly hair hav...
4,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-5,keratoderma with woolly hair,treatment,What are the treatments for keratoderma with w...,These resources address the diagnosis or manag...

In [5]:
df.columns

Index(['document_id', 'document_source', 'document_url', 'category',
       'umls_cui', 'umls_semantic_types', 'umls_semantic_group', 'synonyms',
       'question_id', 'question_focus', 'question_type', 'question', 'answer'],
      dtype='object')

In [6]:
type(dataset)
type(dataset["train"])
dataset["train"][0]

{'document_id': '0000559',
 'document_source': 'GHR',
 'document_url': 'https://ghr.nlm.nih.gov/condition/keratoderma-with-woolly-hair',
 'category': None,
 'umls_cui': 'C0343073',
 'umls_semantic_types': 'T047',
 'umls_semantic_group': 'Disorders',
 'synonyms': 'KWWH',
 'question_id': '0000559-1',
 'question_focus': 'keratoderma with woolly hair',
 'question_type': 'information',
 'question': 'What is (are) keratoderma with woolly hair ?',
 'answer': 'Keratoderma with woolly hair is a group of related conditions that affect the skin and hair and in many cases increase the risk of potentially life-threatening heart problems. People with these conditions have hair that is unusually coarse, dry, fine, and tightly curled. In some cases, the hair is also sparse. The woolly hair texture typically affects only scalp hair and is present from birth. Starting early in life, affected individuals also develop palmoplantar keratoderma, a condition that causes skin on the palms of the hands and the soles of the feet to become thick, scaly, and calloused.  Cardiomyopathy, which is a disease of the heart muscle, is a life-threatening health problem that can develop in people with keratoderma with woolly hair. Unlike the other features of this condition, signs and symptoms of cardiomyopathy may not appear until adolescence or later. Complications of cardiomyopathy can include an abnormal heartbeat (arrhythmia), heart failure, and sudden death.  Keratoderma with woolly hair comprises several related conditions with overlapping signs and symptoms. Researchers have recently proposed classifying keratoderma with woolly hair into four types, based on the underlying genetic cause. Type I, also known as Naxos disease, is characterized by palmoplantar keratoderma, woolly hair, and a form of cardiomyopathy called arrhythmogenic right ventricular cardiomyopathy (ARVC). Type II, also known as Carvajal syndrome, has hair and skin abnormalities similar to type I but features a different form of cardiomyopathy, called dilated left ventricular cardiomyopathy. Type III also has signs and symptoms similar to those of type I, including ARVC, although the hair and skin abnormalities are often milder. Type IV is characterized by palmoplantar keratoderma and woolly and sparse hair, as well as abnormal fingernails and toenails. Type IV does not appear to cause cardiomyopathy.'}

In [7]:
dataset = dataset["train"]

dataset = dataset.remove_columns([
    col for col in dataset.column_names
    if col not in ["question", "answer"]
])

In [8]:
dataset[0]
dataset.column_names

['question', 'answer']

In [9]:
def format_example(example):
    return {
        "text": f"### Instruction:\n{example['question']}\n\n### Response:\n{example['answer']}"
    }

formatted_dataset = dataset.map(format_example)

Map:   0%|          | 0/47441 [00:00<?, ? examples/s]

In [10]:
formatted_dataset[0]
formatted_dataset.column_names

['question', 'answer', 'text']

In [11]:
formatted_dataset = formatted_dataset.remove_columns(["question", "answer"])
formatted_dataset.column_names
formatted_dataset[0]

{'text': '### Instruction:\nWhat is (are) keratoderma with woolly hair ?\n\n### Response:\nKeratoderma with woolly hair is a group of related conditions that affect the skin and hair and in many cases increase the risk of potentially life-threatening heart problems. People with these conditions have hair that is unusually coarse, dry, fine, and tightly curled. In some cases, the hair is also sparse. The woolly hair texture typically affects only scalp hair and is present from birth. Starting early in life, affected individuals also develop palmoplantar keratoderma, a condition that causes skin on the palms of the hands and the soles of the feet to become thick, scaly, and calloused.  Cardiomyopathy, which is a disease of the heart muscle, is a life-threatening health problem that can develop in people with keratoderma with woolly hair. Unlike the other features of this condition, signs and symptoms of cardiomyopathy may not appear until adolescence or later. Complications of cardiomyopathy can include an abnormal heartbeat (arrhythmia), heart failure, and sudden death.  Keratoderma with woolly hair comprises several related conditions with overlapping signs and symptoms. Researchers have recently proposed classifying keratoderma with woolly hair into four types, based on the underlying genetic cause. Type I, also known as Naxos disease, is characterized by palmoplantar keratoderma, woolly hair, and a form of cardiomyopathy called arrhythmogenic right ventricular cardiomyopathy (ARVC). Type II, also known as Carvajal syndrome, has hair and skin abnormalities similar to type I but features a different form of cardiomyopathy, called dilated left ventricular cardiomyopathy. Type III also has signs and symptoms similar to those of type I, including ARVC, although the hair and skin abnormalities are often milder. Type IV is characterized by palmoplantar keratoderma and woolly and sparse hair, as well as abnormal fingernails and toenails. Type IV does not appear to cause cardiomyopathy.'}

In [18]:
formatted_dataset.save_to_disk("medquad_formatted")

Saving the dataset (0/1 shards):   0%|          | 0/47441 [00:00<?, ? examples/s]

In [19]:
import pandas as pd

df = pd.DataFrame(formatted_dataset)
df.to_csv("medquad_formatted.csv", index=False)

In [20]:
print("Rows before filtering:", len(dataset))

dataset = dataset.filter(
    lambda x: x["question"] is not None and x["answer"] is not None
)

dataset = dataset.filter(
    lambda x: x["question"].strip() != "" and x["answer"].strip() != ""
)

print("Rows after filtering:", len(dataset))

Rows before filtering: 47441

Filter:   0%|          | 0/47441 [00:00<?, ? examples/s]

Filter:   0%|          | 0/16407 [00:00<?, ? examples/s]

Rows after filtering: 16407

In [21]:
df = dataset.to_pandas()
print("Exact duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

Exact duplicate rows: 48

In [22]:
from datasets import Dataset

dataset = Dataset.from_pandas(df, preserve_index=False)

In [23]:
dup_q = df.duplicated(subset=["question"]).sum()
print("Duplicate questions:", dup_q)

Duplicate questions: 1380

In [24]:
df = dataset.to_pandas()

df["question_len_chars"] = df["question"].str.len()
df["answer_len_chars"] = df["answer"].str.len()

print(df[["question_len_chars", "answer_len_chars"]].describe())

       question_len_chars  answer_len_chars
count        16359.000000      16359.000000
mean            50.717709       1296.719726
std             16.925605       1645.411318
min             16.000000          6.000000
25%             38.000000        486.000000
50%             48.000000        888.000000
75%             61.000000       1583.500000
max            191.000000      29046.000000

In [25]:
df.sort_values("answer_len_chars", ascending=False)[["question", "answer_len_chars"]].head(10)

                                                question  answer_len_chars
12602        What are the treatments for Breast Cancer ?             29046
12472          What is (are) Childhood Vascular Tumors ?             27910
12416  What are the treatments for Childhood Soft Tis...             27610
12764  What are the treatments for Sickle Cell Disease ?             24733
12464  What are the treatments for Childhood Acute Ly...             23659
12424  What are the treatments for Childhood Acute My...             23540
12226  What are the treatments for Adult Central Nerv...             23065
11913  What are the treatments for Non-Small Cell Lun...             23060
12471  What are the treatments for Childhood Rhabdomy...             22975
12959  What are the treatments for Overweight and Obe...             22218

In [26]:
def clean_text(example):
    q = " ".join(example["question"].split())
    a = " ".join(example["answer"].split())
    return {"question": q, "answer": a}

dataset = dataset.map(clean_text)

Map:   0%|          | 0/16359 [00:00<?, ? examples/s]

In [27]:
def format_example(example):
    return {
        "text": f"Question: {example['question']}\nAnswer: {example['answer']}"
    }

In [28]:
print("Number of rows:", len(dataset))
print("Column names:", dataset.column_names)
print("Dataset type:", type(dataset))

Number of rows: 16359
Column names: ['question', 'answer']
Dataset type: <class 'datasets.arrow_dataset.Dataset'>

In [29]:
from datasets import load_dataset, Dataset

# 1. Load raw dataset
raw_dataset = load_dataset("lavita/MedQuAD")["train"]
print("Raw rows:", len(raw_dataset))
print("Raw columns:", raw_dataset.column_names)

# 2. Keep only the columns needed for training
dataset = raw_dataset.remove_columns([
    col for col in raw_dataset.column_names
    if col not in ["question", "answer"]
])
print("\nAfter keeping only question/answer:", len(dataset))
print("Columns:", dataset.column_names)

# 3. Remove rows with null values
dataset = dataset.filter(
    lambda x: x["question"] is not None and x["answer"] is not None
)
print("\nAfter removing nulls:", len(dataset))

# 4. Remove rows with empty strings
dataset = dataset.filter(
    lambda x: x["question"].strip() != "" and x["answer"].strip() != ""
)
print("After removing empty strings:", len(dataset))

# 5. Normalize whitespace
def clean_text(example):
    return {
        "question": " ".join(example["question"].split()),
        "answer": " ".join(example["answer"].split())
    }

dataset = dataset.map(clean_text)
print("After whitespace cleanup:", len(dataset))

# 6. Remove only exact duplicate rows, not duplicate questions
df = dataset.to_pandas()
print("\nExact duplicate rows before removal:", df.duplicated().sum())
print("Duplicate questions (for inspection only):", df.duplicated(subset=["question"]).sum())

df = df.drop_duplicates()
dataset = Dataset.from_pandas(df, preserve_index=False)

print("\nAfter removing exact duplicate rows:", len(dataset))
print("Final columns:", dataset.column_names)

# 7. Show one sample
print("\nSample row:")
print(dataset[0])

Raw rows: 47441
Raw columns: ['document_id', 'document_source', 'document_url', 'category', 'umls_cui', 'umls_semantic_types', 'umls_semantic_group', 'synonyms', 'question_id', 'question_focus', 'question_type', 'question', 'answer']

After keeping only question/answer: 47441
Columns: ['question', 'answer']

After removing nulls: 16407
After removing empty strings: 16407

Map:   0%|          | 0/16407 [00:00<?, ? examples/s]

After whitespace cleanup: 16407

Exact duplicate rows before removal: 48
Duplicate questions (for inspection only): 1428

After removing exact duplicate rows: 16359
Final columns: ['question', 'answer']

Sample row:
{'question': 'What is (are) keratoderma with woolly hair ?', 'answer': 'Keratoderma with woolly hair is a group of related conditions that affect the skin and hair and in many cases increase the risk of potentially life-threatening heart problems. People with these conditions have hair that is unusually coarse, dry, fine, and tightly curled. In some cases, the hair is also sparse. The woolly hair texture typically affects only scalp hair and is present from birth. Starting early in life, affected individuals also develop palmoplantar keratoderma, a condition that causes skin on the palms of the hands and the soles of the feet to become thick, scaly, and calloused. Cardiomyopathy, which is a disease of the heart muscle, is a life-threatening health problem that can develop in people with keratoderma with woolly hair. Unlike the other features of this condition, signs and symptoms of cardiomyopathy may not appear until adolescence or later. Complications of cardiomyopathy can include an abnormal heartbeat (arrhythmia), heart failure, and sudden death. Keratoderma with woolly hair comprises several related conditions with overlapping signs and symptoms. Researchers have recently proposed classifying keratoderma with woolly hair into four types, based on the underlying genetic cause. Type I, also known as Naxos disease, is characterized by palmoplantar keratoderma, woolly hair, and a form of cardiomyopathy called arrhythmogenic right ventricular cardiomyopathy (ARVC). Type II, also known as Carvajal syndrome, has hair and skin abnormalities similar to type I but features a different form of cardiomyopathy, called dilated left ventricular cardiomyopathy. Type III also has signs and symptoms similar to those of type I, including ARVC, although the hair and skin abnormalities are often milder. Type IV is characterized by palmoplantar keratoderma and woolly and sparse hair, as well as abnormal fingernails and toenails. Type IV does not appear to cause cardiomyopathy.'}

In [30]:
from datasets import load_dataset

raw_dataset = load_dataset("lavita/MedQuAD")["train"]
print("Raw rows:", len(raw_dataset))

dataset = raw_dataset.remove_columns([
    col for col in raw_dataset.column_names
    if col not in ["question", "answer"]
])
print("After keeping only question/answer:", len(dataset))

null_question = dataset.filter(lambda x: x["question"] is None)
null_answer = dataset.filter(lambda x: x["answer"] is None)
print("Rows with question=None:", len(null_question))
print("Rows with answer=None:", len(null_answer))

nonnull_dataset = dataset.filter(
    lambda x: x["question"] is not None and x["answer"] is not None
)
print("After removing nulls:", len(nonnull_dataset))

empty_question = nonnull_dataset.filter(lambda x: x["question"].strip() == "")
empty_answer = nonnull_dataset.filter(lambda x: x["answer"].strip() == "")
print("Rows with empty question:", len(empty_question))
print("Rows with empty answer:", len(empty_answer))

Raw rows: 47441
After keeping only question/answer: 47441

Filter:   0%|          | 0/47441 [00:00<?, ? examples/s]

Filter:   0%|          | 0/47441 [00:00<?, ? examples/s]

Rows with question=None: 0
Rows with answer=None: 31034
After removing nulls: 16407

Filter:   0%|          | 0/16407 [00:00<?, ? examples/s]

Filter:   0%|          | 0/16407 [00:00<?, ? examples/s]

Rows with empty question: 0
Rows with empty answer: 0

In [31]:
pwd

'/Users/vishal/Career/Projects/Medical-Q-A-Chatbot/data/processed'

In [32]:
import os
dataset.save_to_disk("medquad_qa_clean")

Saving the dataset (0/1 shards):   0%|          | 0/47441 [00:00<?, ? examples/s]

In [33]:
def format_example(example):
    return {
        "text": f"### Question:\n{example['question']}\n\n### Answer:\n{example['answer']}"
    }

formatted_dataset = dataset.map(format_example)
formatted_dataset = formatted_dataset.remove_columns(["question", "answer"])
formatted_dataset.save_to_disk("medquad_formatted")

Map:   0%|          | 0/47441 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/47441 [00:00<?, ? examples/s]